---
title: "Seminario_Accidentes"
author: "Lorena Nerín y Lucía González"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Introdcucción**
Las enfermedades laborales

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

# **Descarga de archivos**
```{r, eval=FALSE}
# Instalar la librería readxl si no la tienes
#install.packages("readxl")
library(readxl)
# URL cruda del archivo Excel en GitHub
url <- "https://github.com/Lucia-G-R/Seminario_Fuentes/blob/main/INPUT/DATA/Accidentes_laborales_Canarias.csv.csv"
# Crear un archivo temporal para almacenar el Excel
temp <- tempfile(fileext = ".xlsx")
# Descargar el archivo desde GitHub
download.file("https://datos.gob.es/es/catalogo/a02002834-accidentes-en-jornada-de-trabajo-n-de-accidentes-segun-grado-de-lesion-y-sexo", destfile = "INPUT/DATA/Accidentes_laborales_Canarias.csv.csv" , mode = "wb")
```


```{r, eval=FALSE}

```


```{r, eval=FALSE}

```


```{r, eval=FALSE}

```
